# Generated by Django 6.0.1 on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PixelEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("client_id", models.CharField(db_index=True, max_length=64)),
                ("session_id", models.CharField(db_index=True, max_length=64)),
                ("event_type", models.CharField(db_index=True, max_length=32)),
                ("ts", models.DateTimeField(db_index=True)),
                ("url", models.TextField()),
                ("meta", models.JSONField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("ip", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["-ts"], name="px_ts_desc"),
                    models.Index(fields=["client_id", "session_id"], name="px_client_session"),
                ],
            },
        ),
    ]
